version: '2'
services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4444:4444"
    logging:
      driver: none
  selenium-chrome:
    # Uncomment the next line for a VNC server you can attach to
    # image: selenium/node-chrome-debug
    image: selenium/node-chrome
    ports:
      - "5900:5900"
    depends_on:
      - selenium-hub
    links:
      - "selenium-hub:hub"
      - "dev-server:dev"
    environment:
        - HUB_PORT_4444_TCP_ADDR=hub
    logging:
      driver: none
  dev-server:
    image: joscha/atlaskit
    volumes:
      - .:/usr/src/app/
    ports:
      - "9001:9001"
    environment:
      SCOPE:
    command: 'bash -c
            "
              npm run lerna/link
              && npm run storybook/single \"$SCOPE\"
            "'
  cucumber:
    image: joscha/atlaskit
    volumes:
      - .:/usr/src/app/
    depends_on:
      - selenium-chrome
      - dev-server
    links:
      - "dev-server:dev"
      - "selenium-hub:hub"
    environment:
      SELENIUM_ADDRESS: "http://hub:4444/wd/hub"
      BASE_URL: "http://dev:9001"
      SCOPE:
    command: 'bash -c
            "
              echo \"waiting for hub\"
              && `npm bin`/wait-on tcp:hub:4444
              && echo \"waiting for dev\"
              && `npm bin`/wait-on tcp:dev:9001
              && echo \"running tests\"
              && npm run test/single/integration \"$SCOPE\"
             "'
