# Run this via:
# docker-compose -f docker-compose-test.yml up --force-recreate
version: '2'
services:
  atlaskit-unit-tests:
    build:
      context: .
    image: atlassianlabs/atlaskit:2016-11-14-yarn # You can disable this, to use the local docker file
    volumes:
      - .:/usr/src/app/
    command: 'bash -c "yarn run postinstall && yarn test"' # yarn run postinstall is needed to set up the symlinks between packages correctly in docker
