// flow-typed signature: e4a813708620b5f8eb12ad2d81b3a789
// flow-typed version: <<STUB>>/babel-plugin-react-flow-props-to-prop-types_v0.14/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-react-flow-props-to-prop-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-react-flow-props-to-prop-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-react-flow-props-to-prop-types/lib/convertTypeToPropTypes' {
  declare module.exports: any;
}
