// flow-typed signature: 85bef3127cfeae64ce08b22851667100
// flow-typed version: <<STUB>>/chromatism_v2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chromatism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chromatism' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chromatism/dist/chromatism.esm' {
  declare module.exports: any;
}

declare module 'chromatism/dist/chromatism' {
  declare module.exports: any;
}

declare module 'chromatism/rollup.config' {
  declare module.exports: any;
}

declare module 'chromatism/src/api' {
  declare module.exports: any;
}

declare module 'chromatism/src/constants' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromCieLab' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromCieLch' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromCieLuv' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromCmyk' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromCssHsl' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromCssRgb' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromHex' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromHsl' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromHsluv' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromHsv' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromLMS' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromRgb' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromxyY' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromXYZ' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/fromYiq' {
  declare module.exports: any;
}

declare module 'chromatism/src/conversions/index' {
  declare module.exports: any;
}

declare module 'chromatism/src/entry' {
  declare module.exports: any;
}

declare module 'chromatism/src/helpers' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/adapt' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/adjacent' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/brightness' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/complementary' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/contrast' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/contrastRatio' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/convert' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/difference' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/fade' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/greyscale' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/hue' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/index' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/invert' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/invertLightness' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/mid' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/multiply' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/saturation' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/sepia' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/shade' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/temperature' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/tetrad' {
  declare module.exports: any;
}

declare module 'chromatism/src/operations/triad' {
  declare module.exports: any;
}

declare module 'chromatism/test/consts' {
  declare module.exports: any;
}

declare module 'chromatism/test/rounding' {
  declare module.exports: any;
}

declare module 'chromatism/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chromatism/dist/chromatism.esm.js' {
  declare module.exports: $Exports<'chromatism/dist/chromatism.esm'>;
}
declare module 'chromatism/dist/chromatism.js' {
  declare module.exports: $Exports<'chromatism/dist/chromatism'>;
}
declare module 'chromatism/rollup.config.js' {
  declare module.exports: $Exports<'chromatism/rollup.config'>;
}
declare module 'chromatism/src/api.js' {
  declare module.exports: $Exports<'chromatism/src/api'>;
}
declare module 'chromatism/src/constants.js' {
  declare module.exports: $Exports<'chromatism/src/constants'>;
}
declare module 'chromatism/src/conversions/fromCieLab.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromCieLab'>;
}
declare module 'chromatism/src/conversions/fromCieLch.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromCieLch'>;
}
declare module 'chromatism/src/conversions/fromCieLuv.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromCieLuv'>;
}
declare module 'chromatism/src/conversions/fromCmyk.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromCmyk'>;
}
declare module 'chromatism/src/conversions/fromCssHsl.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromCssHsl'>;
}
declare module 'chromatism/src/conversions/fromCssRgb.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromCssRgb'>;
}
declare module 'chromatism/src/conversions/fromHex.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromHex'>;
}
declare module 'chromatism/src/conversions/fromHsl.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromHsl'>;
}
declare module 'chromatism/src/conversions/fromHsluv.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromHsluv'>;
}
declare module 'chromatism/src/conversions/fromHsv.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromHsv'>;
}
declare module 'chromatism/src/conversions/fromLMS.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromLMS'>;
}
declare module 'chromatism/src/conversions/fromRgb.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromRgb'>;
}
declare module 'chromatism/src/conversions/fromxyY.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromxyY'>;
}
declare module 'chromatism/src/conversions/fromXYZ.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromXYZ'>;
}
declare module 'chromatism/src/conversions/fromYiq.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/fromYiq'>;
}
declare module 'chromatism/src/conversions/index.js' {
  declare module.exports: $Exports<'chromatism/src/conversions/index'>;
}
declare module 'chromatism/src/entry.js' {
  declare module.exports: $Exports<'chromatism/src/entry'>;
}
declare module 'chromatism/src/helpers.js' {
  declare module.exports: $Exports<'chromatism/src/helpers'>;
}
declare module 'chromatism/src/operations/adapt.js' {
  declare module.exports: $Exports<'chromatism/src/operations/adapt'>;
}
declare module 'chromatism/src/operations/adjacent.js' {
  declare module.exports: $Exports<'chromatism/src/operations/adjacent'>;
}
declare module 'chromatism/src/operations/brightness.js' {
  declare module.exports: $Exports<'chromatism/src/operations/brightness'>;
}
declare module 'chromatism/src/operations/complementary.js' {
  declare module.exports: $Exports<'chromatism/src/operations/complementary'>;
}
declare module 'chromatism/src/operations/contrast.js' {
  declare module.exports: $Exports<'chromatism/src/operations/contrast'>;
}
declare module 'chromatism/src/operations/contrastRatio.js' {
  declare module.exports: $Exports<'chromatism/src/operations/contrastRatio'>;
}
declare module 'chromatism/src/operations/convert.js' {
  declare module.exports: $Exports<'chromatism/src/operations/convert'>;
}
declare module 'chromatism/src/operations/difference.js' {
  declare module.exports: $Exports<'chromatism/src/operations/difference'>;
}
declare module 'chromatism/src/operations/fade.js' {
  declare module.exports: $Exports<'chromatism/src/operations/fade'>;
}
declare module 'chromatism/src/operations/greyscale.js' {
  declare module.exports: $Exports<'chromatism/src/operations/greyscale'>;
}
declare module 'chromatism/src/operations/hue.js' {
  declare module.exports: $Exports<'chromatism/src/operations/hue'>;
}
declare module 'chromatism/src/operations/index.js' {
  declare module.exports: $Exports<'chromatism/src/operations/index'>;
}
declare module 'chromatism/src/operations/invert.js' {
  declare module.exports: $Exports<'chromatism/src/operations/invert'>;
}
declare module 'chromatism/src/operations/invertLightness.js' {
  declare module.exports: $Exports<'chromatism/src/operations/invertLightness'>;
}
declare module 'chromatism/src/operations/mid.js' {
  declare module.exports: $Exports<'chromatism/src/operations/mid'>;
}
declare module 'chromatism/src/operations/multiply.js' {
  declare module.exports: $Exports<'chromatism/src/operations/multiply'>;
}
declare module 'chromatism/src/operations/saturation.js' {
  declare module.exports: $Exports<'chromatism/src/operations/saturation'>;
}
declare module 'chromatism/src/operations/sepia.js' {
  declare module.exports: $Exports<'chromatism/src/operations/sepia'>;
}
declare module 'chromatism/src/operations/shade.js' {
  declare module.exports: $Exports<'chromatism/src/operations/shade'>;
}
declare module 'chromatism/src/operations/temperature.js' {
  declare module.exports: $Exports<'chromatism/src/operations/temperature'>;
}
declare module 'chromatism/src/operations/tetrad.js' {
  declare module.exports: $Exports<'chromatism/src/operations/tetrad'>;
}
declare module 'chromatism/src/operations/triad.js' {
  declare module.exports: $Exports<'chromatism/src/operations/triad'>;
}
declare module 'chromatism/test/consts.js' {
  declare module.exports: $Exports<'chromatism/test/consts'>;
}
declare module 'chromatism/test/rounding.js' {
  declare module.exports: $Exports<'chromatism/test/rounding'>;
}
declare module 'chromatism/test/test.js' {
  declare module.exports: $Exports<'chromatism/test/test'>;
}
