// flow-typed signature: 85bef3127cfeae64ce08b22851667100
// flow-typed version: <<STUB>>/chromatism_v2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chromatism'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chromatism' {
  declare module.exports: any;
}
