// flow-typed signature: c971093db737d29bd486dc0126d70566
// flow-typed version: <<STUB>>/faker_v4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'faker'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'faker' {
  declare module.exports: any;
}
