// flow-typed signature: eda6e7405f1b07d8fa1573675b2cf823
// flow-typed version: <<STUB>>/memoize-one_v3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memoize-one'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memoize-one' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memoize-one/lib/index' {
  declare module.exports: any;
}

declare module 'memoize-one/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memoize-one/lib/index.js' {
  declare module.exports: $Exports<'memoize-one/lib/index'>;
}
declare module 'memoize-one/src/index.js' {
  declare module.exports: $Exports<'memoize-one/src/index'>;
}
