// flow-typed signature: e2ccd1289c5ab4758f5143c1cda56cc5
// flow-typed version: <<STUB>>/polished_v1.3/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polished'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polished' {
  declare module.exports: any;
}
