// flow-typed signature: 7f3587f9449373d47737bcaa99a99ae4
// flow-typed version: <<STUB>>/raf-stub_v2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf-stub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raf-stub' {
  declare module.exports: any;
}
