// flow-typed signature: 7f3587f9449373d47737bcaa99a99ae4
// flow-typed version: <<STUB>>/raf-stub_v2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf-stub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raf-stub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raf-stub/lib/constants' {
  declare module.exports: any;
}

declare module 'raf-stub/lib/index' {
  declare module.exports: any;
}

declare module 'raf-stub/src/constants' {
  declare module.exports: any;
}

declare module 'raf-stub/src/index' {
  declare module.exports: any;
}

declare module 'raf-stub/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raf-stub/lib/constants.js' {
  declare module.exports: $Exports<'raf-stub/lib/constants'>;
}
declare module 'raf-stub/lib/index.js' {
  declare module.exports: $Exports<'raf-stub/lib/index'>;
}
declare module 'raf-stub/src/constants.js' {
  declare module.exports: $Exports<'raf-stub/src/constants'>;
}
declare module 'raf-stub/src/index.js' {
  declare module.exports: $Exports<'raf-stub/src/index'>;
}
declare module 'raf-stub/test/index.js' {
  declare module.exports: $Exports<'raf-stub/test/index'>;
}
