// flow-typed signature: 08dc97edcf937278f27a4fb0b6322d4a
// flow-typed version: <<STUB>>/raf-schd_v2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'raf-schd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'raf-schd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'raf-schd/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'raf-schd/lib/index' {
  declare module.exports: any;
}

declare module 'raf-schd/src/index' {
  declare module.exports: any;
}

declare module 'raf-schd/test/index.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'raf-schd/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'raf-schd/flow-typed/npm/jest_v20.x.x'>;
}
declare module 'raf-schd/lib/index.js' {
  declare module.exports: $Exports<'raf-schd/lib/index'>;
}
declare module 'raf-schd/src/index.js' {
  declare module.exports: $Exports<'raf-schd/src/index'>;
}
declare module 'raf-schd/test/index.spec.js' {
  declare module.exports: $Exports<'raf-schd/test/index.spec'>;
}
