// flow-typed signature: a5b0bc517c8699652091c7f84fba309b
// flow-typed version: <<STUB>>/react-markdown_v2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}
