// flow-typed signature: e31fbbdfb51984f207706448c9ae06b3
// flow-typed version: <<STUB>>/semver_v5/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semver'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semver' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semver/semver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semver/semver.js' {
  declare module.exports: $Exports<'semver/semver'>;
}
