// flow-typed signature: f6c822f0e1f18cddb005af86c047528f
// flow-typed version: <<STUB>>/@atlaskit/util-readme_v^1.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/util-readme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/util-readme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/util-readme/src/chrome' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/src/code' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/src/description' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/src/heading' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/src/index' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/src/props' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/src/readme' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/chrome' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/code' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/description1' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/description2' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/heading1' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/heading2' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/overview' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/props' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/readme1' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/examples/readme2' {
  declare module.exports: any;
}

declare module '@atlaskit/util-readme/stories/index-story' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/util-readme/src/chrome.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/src/chrome'>;
}
declare module '@atlaskit/util-readme/src/code.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/src/code'>;
}
declare module '@atlaskit/util-readme/src/description.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/src/description'>;
}
declare module '@atlaskit/util-readme/src/heading.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/src/heading'>;
}
declare module '@atlaskit/util-readme/src/index.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/src/index'>;
}
declare module '@atlaskit/util-readme/src/props.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/src/props'>;
}
declare module '@atlaskit/util-readme/src/readme.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/src/readme'>;
}
declare module '@atlaskit/util-readme/stories/examples/chrome.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/chrome'>;
}
declare module '@atlaskit/util-readme/stories/examples/code.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/code'>;
}
declare module '@atlaskit/util-readme/stories/examples/description1.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/description1'>;
}
declare module '@atlaskit/util-readme/stories/examples/description2.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/description2'>;
}
declare module '@atlaskit/util-readme/stories/examples/heading1.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/heading1'>;
}
declare module '@atlaskit/util-readme/stories/examples/heading2.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/heading2'>;
}
declare module '@atlaskit/util-readme/stories/examples/overview.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/overview'>;
}
declare module '@atlaskit/util-readme/stories/examples/props.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/props'>;
}
declare module '@atlaskit/util-readme/stories/examples/readme1.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/readme1'>;
}
declare module '@atlaskit/util-readme/stories/examples/readme2.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/examples/readme2'>;
}
declare module '@atlaskit/util-readme/stories/index-story.jsx' {
  declare module.exports: $Exports<'@atlaskit/util-readme/stories/index-story'>;
}
