// flow-typed signature: 4b358ae34f7ffcd06a9d947d8080b6cf
// flow-typed version: <<STUB>>/@atlaskit/util-shared-styles_v^1.0.1/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atlaskit/util-shared-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@atlaskit/util-shared-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atlaskit/util-shared-styles/src/index' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/00_color-story' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/animation-story' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/animation/AnimatedBox' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/animation/AnimatedBoxGroup' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/color/Block' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/color/Blocks' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/slot-children-story' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/slot-children/slot-component' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/stories/typography-story' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/test/_Prism' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/test/exports' {
  declare module.exports: any;
}

declare module '@atlaskit/util-shared-styles/test/Prism' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atlaskit/util-shared-styles/src/index.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/src/index'>;
}
declare module '@atlaskit/util-shared-styles/stories/00_color-story.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/00_color-story'>;
}
declare module '@atlaskit/util-shared-styles/stories/animation-story.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/animation-story'>;
}
declare module '@atlaskit/util-shared-styles/stories/animation/AnimatedBox.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/animation/AnimatedBox'>;
}
declare module '@atlaskit/util-shared-styles/stories/animation/AnimatedBoxGroup.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/animation/AnimatedBoxGroup'>;
}
declare module '@atlaskit/util-shared-styles/stories/color/Block.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/color/Block'>;
}
declare module '@atlaskit/util-shared-styles/stories/color/Blocks.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/color/Blocks'>;
}
declare module '@atlaskit/util-shared-styles/stories/slot-children-story.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/slot-children-story'>;
}
declare module '@atlaskit/util-shared-styles/stories/slot-children/slot-component.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/slot-children/slot-component'>;
}
declare module '@atlaskit/util-shared-styles/stories/typography-story.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/stories/typography-story'>;
}
declare module '@atlaskit/util-shared-styles/test/_Prism.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/test/_Prism'>;
}
declare module '@atlaskit/util-shared-styles/test/exports.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/test/exports'>;
}
declare module '@atlaskit/util-shared-styles/test/Prism.js' {
  declare module.exports: $Exports<'@atlaskit/util-shared-styles/test/Prism'>;
}
