module.exports = {
  'app-switcher': 'menu',
  'arrow-right-long': 'arrow-right',
  cancel: 'cross',
  confirm: 'check',
  expand: 'chevron-down',
  help: 'question-circle',
  hint: 'lightbulb-filled',
  'hipchat/media-uploader': 'upload',
  'log-in': 'sign-in',
  'media-services/square': 'media-services/rectangle',
  remove: 'trash',
  'schedule-add': 'schedule',
  time: 'recent',
};
