/* eslint-disable global-require, quote-props */
/**
 * NOTE:
 *
 * This file is automatically generated by the build process.
 * DO NOT CHANGE IT BY HAND or your changes will be lost.
 *
 * To change the format of this file, modify website/build/data.template.js.
 */

/* eslint-disable import/no-duplicates, import/first */
import FocusedTaskExample from './patterns/FocusedTaskExample';
import FocusedTaskExampleSrc from '!raw-loader!./patterns/FocusedTaskExample';
import NavCollapseExample from './patterns/NavCollapseExample';
import NavCollapseExampleSrc from '!raw-loader!./patterns/NavCollapseExample';
import NavComplexExample from './patterns/NavComplexExample';
import NavComplexExampleSrc from '!raw-loader!./patterns/NavComplexExample';
import NavDrawerExample from './patterns/NavDrawerExample';
import NavDrawerExampleSrc from '!raw-loader!./patterns/NavDrawerExample';
import NavSimpleExample from './patterns/NavSimpleExample';
import NavSimpleExampleSrc from '!raw-loader!./patterns/NavSimpleExample';
import NavThemedExample from './patterns/NavThemedExample';
import NavThemedExampleSrc from '!raw-loader!./patterns/NavThemedExample';
import PatternExample from './patterns/PatternExample';
import PatternExampleSrc from '!raw-loader!./patterns/PatternExample';
import index from './patterns/index';
import indexSrc from '!raw-loader!./patterns/index';

/* eslint-enable import/no-duplicates, import/first */

const examples = [
  {
    title: FocusedTaskExample,
    Component: FocusedTaskExample,
    src: FocusedTaskExampleSrc,
  },
  {
    title: NavCollapseExample,
    Component: NavCollapseExample,
    src: NavCollapseExampleSrc,
  },
  {
    title: NavComplexExample,
    Component: NavComplexExample,
    src: NavComplexExampleSrc,
  },
  {
    title: NavDrawerExample,
    Component: NavDrawerExample,
    src: NavDrawerExampleSrc,
  },
  {
    title: NavSimpleExample,
    Component: NavSimpleExample,
    src: NavSimpleExampleSrc,
  },
  {
    title: NavThemedExample,
    Component: NavThemedExample,
    src: NavThemedExampleSrc,
  },
  {
    title: PatternExample,
    Component: PatternExample,
    src: PatternExampleSrc,
  },
  {
    title: index,
    Component: index,
    src: indexSrc,
  },
];

export default examples;
