// NOTE: This file is generated from the glyphs found inside this Component
//       DO NOT MODIFY THIS FILE AS YOUR CHANGES WILL BE OVERRIDDEN

import { size } from './Icon';
import tmpArrowleftIcon from '../src/tmp/arrowleft';
import tmpArrowrightIcon from '../src/tmp/arrowright';
import tmpAtlassianIcon from '../src/tmp/atlassian';
import tmpBitbucketAddonsIcon from '../src/tmp/bitbucket/addons';
import tmpBitbucketAdminIcon from '../src/tmp/bitbucket/admin';
import tmpBitbucketBranchesIcon from '../src/tmp/bitbucket/branches';
import tmpBitbucketBuildsIcon from '../src/tmp/bitbucket/builds';
import tmpBitbucketCommitsIcon from '../src/tmp/bitbucket/commits';
import tmpBitbucketDashboardIcon from '../src/tmp/bitbucket/dashboard';
import tmpBitbucketDownloadsIcon from '../src/tmp/bitbucket/downloads';
import tmpBitbucketFollowersIcon from '../src/tmp/bitbucket/followers';
import tmpBitbucketFollowingIcon from '../src/tmp/bitbucket/following';
import tmpBitbucketIssuesIcon from '../src/tmp/bitbucket/issues';
import tmpBitbucketLogoIcon from '../src/tmp/bitbucket/logo';
import tmpBitbucketMembersIcon from '../src/tmp/bitbucket/members';
import tmpBitbucketOptoutIcon from '../src/tmp/bitbucket/optout';
import tmpBitbucketPipelinesIcon from '../src/tmp/bitbucket/pipelines';
import tmpBitbucketProjectsIcon from '../src/tmp/bitbucket/projects';
import tmpBitbucketPullrequestsIcon from '../src/tmp/bitbucket/pullrequests';
import tmpBitbucketReposIcon from '../src/tmp/bitbucket/repos';
import tmpBitbucketRepositoriesIcon from '../src/tmp/bitbucket/repositories';
import tmpBitbucketSnippetsIcon from '../src/tmp/bitbucket/snippets';
import tmpBitbucketSourceIcon from '../src/tmp/bitbucket/source';
import tmpBitbucketTeamsIcon from '../src/tmp/bitbucket/teams';
import tmpBitbucketWikiIcon from '../src/tmp/bitbucket/wiki';
import tmpCheckboxIcon from '../src/tmp/checkbox';
import tmpConfluenceCalendarIcon from '../src/tmp/confluence/calendar';
import tmpConfluenceCanvasIcon from '../src/tmp/confluence/canvas';
import tmpConfluencePageIcon from '../src/tmp/confluence/page';
import tmpConfluencePersonIcon from '../src/tmp/confluence/person';
import tmpConfluenceQuoteIcon from '../src/tmp/confluence/quote';
import tmpCreateIcon from '../src/tmp/create';
import tmpDashboardIcon from '../src/tmp/dashboard';
import tmpEditIcon from '../src/tmp/edit';
import tmpEditorBoldIcon from '../src/tmp/editor/bold';
import tmpEditorCodeIcon from '../src/tmp/editor/code';
import tmpEditorImageIcon from '../src/tmp/editor/image';
import tmpEditorItalicIcon from '../src/tmp/editor/italic';
import tmpEditorLinkIcon from '../src/tmp/editor/link';
import tmpEditorListBulletIcon from '../src/tmp/editor/list/bullet';
import tmpEditorListNumberIcon from '../src/tmp/editor/list/number';
import tmpEditorMentionIcon from '../src/tmp/editor/mention';
import tmpEditorOpenIcon from '../src/tmp/editor/open';
import tmpEditorUnderlineIcon from '../src/tmp/editor/underline';
import tmpEditorUnlinkIcon from '../src/tmp/editor/unlink';
import tmpErrorIcon from '../src/tmp/error';
import tmpExpandIcon from '../src/tmp/expand';
import tmpFeedbackIcon from '../src/tmp/feedback';
import tmpHelpIcon from '../src/tmp/help';
import tmpHomeIcon from '../src/tmp/home';
import tmpJiraLogoIcon from '../src/tmp/jira/logo';
import tmpMoreoptionsIcon from '../src/tmp/moreoptions';
import tmpProjectsIcon from '../src/tmp/projects';
import tmpQuestionIcon from '../src/tmp/question';
import tmpRadioIcon from '../src/tmp/radio';
import tmpSearchIcon from '../src/tmp/search';
import tmpSettingsIcon from '../src/tmp/settings';
import tmpSuccessIcon from '../src/tmp/success';

export const ArrowleftIcon = tmpArrowleftIcon;
export const ArrowrightIcon = tmpArrowrightIcon;
export const AtlassianIcon = tmpAtlassianIcon;
export const BitbucketAddonsIcon = tmpBitbucketAddonsIcon;
export const BitbucketAdminIcon = tmpBitbucketAdminIcon;
export const BitbucketBranchesIcon = tmpBitbucketBranchesIcon;
export const BitbucketBuildsIcon = tmpBitbucketBuildsIcon;
export const BitbucketCommitsIcon = tmpBitbucketCommitsIcon;
export const BitbucketDashboardIcon = tmpBitbucketDashboardIcon;
export const BitbucketDownloadsIcon = tmpBitbucketDownloadsIcon;
export const BitbucketFollowersIcon = tmpBitbucketFollowersIcon;
export const BitbucketFollowingIcon = tmpBitbucketFollowingIcon;
export const BitbucketIssuesIcon = tmpBitbucketIssuesIcon;
export const BitbucketLogoIcon = tmpBitbucketLogoIcon;
export const BitbucketMembersIcon = tmpBitbucketMembersIcon;
export const BitbucketOptoutIcon = tmpBitbucketOptoutIcon;
export const BitbucketPipelinesIcon = tmpBitbucketPipelinesIcon;
export const BitbucketProjectsIcon = tmpBitbucketProjectsIcon;
export const BitbucketPullrequestsIcon = tmpBitbucketPullrequestsIcon;
export const BitbucketReposIcon = tmpBitbucketReposIcon;
export const BitbucketRepositoriesIcon = tmpBitbucketRepositoriesIcon;
export const BitbucketSnippetsIcon = tmpBitbucketSnippetsIcon;
export const BitbucketSourceIcon = tmpBitbucketSourceIcon;
export const BitbucketTeamsIcon = tmpBitbucketTeamsIcon;
export const BitbucketWikiIcon = tmpBitbucketWikiIcon;
export const CheckboxIcon = tmpCheckboxIcon;
export const ConfluenceCalendarIcon = tmpConfluenceCalendarIcon;
export const ConfluenceCanvasIcon = tmpConfluenceCanvasIcon;
export const ConfluencePageIcon = tmpConfluencePageIcon;
export const ConfluencePersonIcon = tmpConfluencePersonIcon;
export const ConfluenceQuoteIcon = tmpConfluenceQuoteIcon;
export const CreateIcon = tmpCreateIcon;
export const DashboardIcon = tmpDashboardIcon;
export const EditIcon = tmpEditIcon;
export const EditorBoldIcon = tmpEditorBoldIcon;
export const EditorCodeIcon = tmpEditorCodeIcon;
export const EditorImageIcon = tmpEditorImageIcon;
export const EditorItalicIcon = tmpEditorItalicIcon;
export const EditorLinkIcon = tmpEditorLinkIcon;
export const EditorListBulletIcon = tmpEditorListBulletIcon;
export const EditorListNumberIcon = tmpEditorListNumberIcon;
export const EditorMentionIcon = tmpEditorMentionIcon;
export const EditorOpenIcon = tmpEditorOpenIcon;
export const EditorUnderlineIcon = tmpEditorUnderlineIcon;
export const EditorUnlinkIcon = tmpEditorUnlinkIcon;
export const ErrorIcon = tmpErrorIcon;
export const ExpandIcon = tmpExpandIcon;
export const FeedbackIcon = tmpFeedbackIcon;
export const HelpIcon = tmpHelpIcon;
export const HomeIcon = tmpHomeIcon;
export const JiraLogoIcon = tmpJiraLogoIcon;
export const MoreoptionsIcon = tmpMoreoptionsIcon;
export const ProjectsIcon = tmpProjectsIcon;
export const QuestionIcon = tmpQuestionIcon;
export const RadioIcon = tmpRadioIcon;
export const SearchIcon = tmpSearchIcon;
export const SettingsIcon = tmpSettingsIcon;
export const SuccessIcon = tmpSuccessIcon;
export { size };
