// flow-typed signature: 04ad89c882082e8e53360c1695f67f0e
// flow-typed version: <<STUB>>/@kadira/storybook_v2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kadira/storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kadira/storybook' {
  declare module.exports: any;
}
/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kadira/storybook/addons' {
  declare module.exports: any;
}
