export { version, name } from './version';
export { default as Keymap } from 'browserkeymap';
export * from './config';
export * from './media';
export * from './plugins';
export { Schema, NodeType, MarkType } from './prosemirror';
export * from './schema';
export * from './ui';
export * from './analytics';
export type ContextName = 'default';
